### ISSUE TITLE
HRP portfolio API change

### ISSUE THREAD

**Issue by robertmartin8** [firmai/machine-learning-asset-management#2]
Hi Derek,

Robert here. Just wanted to let you know regarding a breaking change I made to PyPortfolioOpt. I changed the API of HRP to bring it in line with the rest of the package (i.e it now inherits from the `BaseOptimizer`). As a result, `HRP.ipynb` needs the following change:

From: 

```python
import numpy as np
from pypfopt.hierarchical_risk_parity import hrp_portfolio

df = pd.read_csv("input/stocks.csv").set_index('date')
df = df.dropna(axis=0)
returns = df.pct_change().dropna(how="all")
w = hrp_portfolio(returns)
```

to:

```python
import numpy as np
from pypfopt.hierarchical_risk_parity import HRPOpt

df = pd.read_csv("input/stocks.csv").set_index('date')
df = df.dropna(axis=0)
returns = df.pct_change().dropna(how="all")
hrp = HRPOpt(returns)
w = hrp.hrp_portfolio()
```

Let me know if there are any issues!

**Comment by firmai** [comment]
Excellent, thank you for the correction.
